// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAI0TTC7Te_1eOV4iywcxpF0oRL9rZWb4',
    appId: '1:623432132497:web:247ddb8c5e023c3a7adc30',
    messagingSenderId: '623432132497',
    projectId: 'plantdiseaserecognition',
    authDomain: 'plantdiseaserecognition.firebaseapp.com',
    storageBucket: 'plantdiseaserecognition.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxH2Fe04KEG1-T3mv2l5visyZmONwSvkU',
    appId: '1:623432132497:android:86157ab71a6688ad7adc30',
    messagingSenderId: '623432132497',
    projectId: 'plantdiseaserecognition',
    storageBucket: 'plantdiseaserecognition.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgS6KjnlPlNANV0trTLkVL_5T4I4bB6gA',
    appId: '1:623432132497:ios:92f6881fc9d498107adc30',
    messagingSenderId: '623432132497',
    projectId: 'plantdiseaserecognition',
    storageBucket: 'plantdiseaserecognition.appspot.com',
    iosBundleId: 'com.aol.ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgS6KjnlPlNANV0trTLkVL_5T4I4bB6gA',
    appId: '1:623432132497:ios:92f6881fc9d498107adc30',
    messagingSenderId: '623432132497',
    projectId: 'plantdiseaserecognition',
    storageBucket: 'plantdiseaserecognition.appspot.com',
    iosBundleId: 'com.aol.ai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAI0TTC7Te_1eOV4iywcxpF0oRL9rZWb4',
    appId: '1:623432132497:web:9d441b17ba2c16427adc30',
    messagingSenderId: '623432132497',
    projectId: 'plantdiseaserecognition',
    authDomain: 'plantdiseaserecognition.firebaseapp.com',
    storageBucket: 'plantdiseaserecognition.appspot.com',
  );
}
